[env]

[tools]
uv = "0.9.18"
lefthook = "2.0.12"
dprint = "0.50.1"
"pipx:pkglink" = { version = "1.0.1" }
"pipx:poethepoet" = { version = "0.38.0" }
"pipx:git+https://github.com/hotdog-werx/releez.git" = "01fa1bb"

[hooks]
# Note: Postinstall hooks do not run in CI, this is intentional.
postinstall = [
  "if [ \"${CI:-}\" = \"true\" ]; then exit 0; fi; pkglink sync",
  "if [ \"${CI:-}\" = \"true\" ]; then exit 0; fi; lefthook install",
]

[settings]
experimental = true
python.uv_venv_auto = true
